/** @format */

export const en = {
  email: "Email",
  password: "Password",
  forgotPassword: "Forgot Password?",
  login: "Login",
  dontHaveAccount: "Don't have an account? ",
  register: "register",
  username: "Username",
  confirmPassword: "Confirm Password",
  agreeToTerms: "I agree to the terms of service",
  alreadyHaveAccount: "Already have an account? ",
  send: "Send",
  emailIsRequired: "Email is required",
  emailIsInvalid: "Email address is invalid",
  passwordIsRequired: "Password is required",
  passwordNeedsToBe6CharactersOrMore:
    "Password needs to be 6 characters or more",
  passwordDoesNotMatch: "Password does not match",
  usernameIsRequired: "Username is required",
  nameNeedsToBe3CharactersOrMore: "Username needs to be 3 characters or more",
  shouldAgreeToTerms: "You should agree to terms",
  somethingWentWrong: "Something went wrong",
  usernameIsTaken: "Username is taken",
  emailIsInUse: "This email is already in use",
  name: "Name",
  nameisrequired: "Name is required",
  surname: "Surname",
  surnameisrequired: "Surname is required",
  surnameNeedsToBe2CharactersOrMore: "Surname needs to be 2 characters or more",
  identitynumber: "Identity Number",
  identitynumberisrequired: "Identity Number is required",
  identitynumberisinvalid: "Identity Number is invalid",
  birthDate: "Birth Date",
  birthdateisrequired: "Birth Date is required",
  gender: "Gender",
  genderisrequired: "Gender is required",
  man: "Man",
  woman: "Woman",
  chooseGender: "ChooseGender",
  registerScreen: "Register",
  forgotPasswordScreen: "Forgot Password",
  identitynumberneedsToBe11Characters:
    "Identity number needs to be 11 characters",
  registerSuccess: "Register Success",
  emailOrPasswordWrong: "Username or password wrong",
  voyages: "Voyages",
  voyageDetail: "Voyage Detail",
  payment: "Payment",
  departureDate: "Departure Date",
  returnDate: "Return Date",
  search: "Search",
  origin: "Origin",
  destination: "Destination",
  roundTrip: "Round Trip",
  departure: "Departure",
  return: "Return",
  pleaseFillAllFields: "Please fill all fields",
  settings: "Settings",
  save: "Save",
  thisFeatureIsNotAvailable: "This feature is not available yet",
  changeLanguage: "Change Language",
  logout: "Logout",
};
