/** @format */

export const tr = {
  email: "E-posta",
  password: "Şifre",
  forgotPassword: "Şifremi Unuttum?",
  login: "Giriş Yap",
  dontHaveAccount: "Hesabın yok mu? ",
  register: "Kayıt Ol",
  username: "Kullanıcı Adı",
  confirmPassword: "Şifreyi Tekrarla",
  agreeToTerms: "Hizmet Şartlarını kabul ediyorum",
  alreadyHaveAccount: "Zaten bir hesabın var mı? ",
  send: "Gönder",
  emailIsRequired: "E-posta gerekli",
  emailIsInvalid: "E-posta adresi geçersiz",
  passwordIsRequired: "Şifre gerekli",
  passwordNeedsToBe6CharactersOrMore: "Şifre 6 karakterden uzun olmalı",
  passwordDoesNotMatch: "Şifre eşleşmiyor",
  usernameIsRequired: "Kullanıcı adı gerekli",
  nameNeedsToBe3CharactersOrMore: "Kullanıcı adı 3 karakterden uzun olmalı",
  shouldAgreeToTerms: "Hizmet Şartlarını kabul etmelisiniz",
  somethingWentWrong: "Bir şeyler yanlış gitti",
  usernameIsTaken: "Kullanıcı adı alınmış",
  emailIsInUse: "Bu e-posta zaten kullanılıyor",
  name: "İsim",
  nameisrequired: "İsim gerekli",
  surname: "Soyisim",
  surnameisrequired: "Soyisim gerekli",
  surnameNeedsToBe2CharactersOrMore: "Soyisim 2 karakterden uzun olmalı",
  identitynumber: "Kimlik Numarası",
  identitynumberisrequired: "Kimlik Numarası gerekli",
  identitynumberisinvalid: "Kimlik Numarası geçersiz",
  birthDate: "Doğum Tarihi",
  birthdateisrequired: "Doğum Tarihi gerekli",
  gender: "Cinsiyet",
  genderisrequired: "Cinsiyet gerekli",
  man: "Erkek",
  woman: "Kadın",
  chooseGender: "Cinsiyet Seç",
  registerScreen: "Kayıt Ol",
  forgotPasswordScreen: "Şifremi Unuttum",
  identitynumberneedsToBe11Characters: "Kimlik numarası 11 karakter olmalı",
  registerSuccess: "Kayıt Başarılı",
  emailOrPasswordWrong: "Kullanıcı adı veya şifre hatalı",
  voyages: "Seferler",
  voyageDetail: "Sefer Detayı",
  payment: "Ödeme",
  departureDate: "Gidiş Tarihi",
  returnDate: "Dönüş Tarihi",
  search: "Ara",
  origin: "Nereden",
  destination: "Nereye",
  roundTrip: "Gidiş Dönüş",
  departure: "Gidiş",
  return: "Dönüş",
  pleaseFillAllFields: "Lütfen tüm alanları doldurun",
  settings: "Ayarlar",
  save: "Kaydet",
  thisFeatureIsNotAvailable: "Bu özellik henüz kullanılamıyor",
  changeLanguage: "Dil Değiştir",
  logout: "Çıkış Yap",
  selectedByAMan: "Bir erkek tarafından seçildi",
  selectedByAWoman: "Bir kadın tarafından seçildi",
  notAvailableSeat: "Koltuk müsait değil",
  availableSeat: "Koltuk müsait",
  selectedSeats: "Seçilen koltuklar:",
  totalPrice: "Toplam Fiyat:",
  goToPayment: "Ödemeye Git",
  canChooseUpTo5Seats: "En fazla 5 koltuk seçebilirsiniz",
  chooseAtLeast1Seat: "En az 1 koltuk seçmelisiniz",
  nameOnCard: "Kart Üzerindeki İsim",
  cardNumber: "Kart Numarası",
  expirationDate: "Son Kullanma Tarihi",
  cvv: "CVV",
  pay: "Ödeme Yap",
  paymentSuccess: "Ödeme Başarılı",
  noVoyageFound: "Sefer bulunamadı",
  thankYouForChoosingUs: "Bizi tercih ettiğiniz için teşekkür ederiz",
  redirectingToHome: "Anasayfaya yönlendiriliyorsunuz",
};
