/** @format */

export const tr = {
  email: "E-posta",
  password: "Şifre",
  forgotPassword: "Şifremi Unuttum?",
  login: "Giriş Yap",
  dontHaveAccount: "Hesabın yok mu? ",
  register: "Kayıt Ol",
  username: "Kullanıcı Adı",
  confirmPassword: "Şifreyi Tekrarla",
  agreeToTerms: "Hizmet Şartlarını kabul ediyorum",
  alreadyHaveAccount: "Zaten bir hesabın var mı? ",
  send: "Gönder",
  emailIsRequired: "E-posta gerekli",
  emailIsInvalid: "E-posta adresi geçersiz",
  passwordIsRequired: "Şifre gerekli",
  passwordNeedsToBe6CharactersOrMore: "Şifre 6 karakterden uzun olmalı",
  passwordDoesNotMatch: "Şifre eşleşmiyor",
  usernameIsRequired: "Kullanıcı adı gerekli",
  nameNeedsToBe3CharactersOrMore: "Kullanıcı adı 3 karakterden uzun olmalı",
  shouldAgreeToTerms: "Hizmet Şartlarını kabul etmelisiniz",
  somethingWentWrong: "Bir şeyler yanlış gitti",
  usernameIsTaken: "Kullanıcı adı alınmış",
  emailIsInUse: "Bu e-posta zaten kullanılıyor",
  name: "İsim",
  nameisrequired: "İsim gerekli",
  surname: "Soyisim",
  surnameisrequired: "Soyisim gerekli",
  surnameNeedsToBe2CharactersOrMore: "Soyisim 2 karakterden uzun olmalı",
  identitynumber: "Kimlik Numarası",
  identitynumberisrequired: "Kimlik Numarası gerekli",
  identitynumberisinvalid: "Kimlik Numarası geçersiz",
  birthDate: "Doğum Tarihi",
  birthdateisrequired: "Doğum Tarihi gerekli",
  gender: "Cinsiyet",
  genderisrequired: "Cinsiyet gerekli",
  man: "Erkek",
  woman: "Kadın",
  chooseGender: "Cinsiyet Seç",
  registerScreen: "Kayıt Ol",
  forgotPasswordScreen: "Şifremi Unuttum",
  identitynumberneedsToBe11Characters: "Kimlik numarası 11 karakter olmalı",
  registerSuccess: "Kayıt Başarılı",
};
